apiVersion: v1
kind: Service
metadata:
  name: nginx-red
spec:
  selector:
    app: nginx-red
  ports:
  - name: https
    port: 443
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-red
spec:
  selector:
    matchLabels:
      app: nginx-red
  template:
    metadata:
      labels:
        app: nginx-red
    spec:
      containers:
      - name: nginx-red
        image: nginx:latest
        ports:
        - containerPort: 443
        volumeMounts:
        - name: conf
          mountPath: /etc/nginx
          readOnly: true
        - name: conf
          mountPath: /usr/share/nginx/html
          readOnly: true
        - name: nginx-server-certs-red
          mountPath: /etc/mycerts
          readOnly: true
      volumes:
      - name: conf
        configMap:
          name: nginx-configmap-red
      - name: nginx-server-certs-red
        secret:
          secretName: nginx-server-certs-red
        